
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ .Values.pvc.namespace }}
spec: 
  storageClassName: {{ .Values.pvc.scclass }}
  accessModes:
    - {{ .Values.pvc.access }}
  resources:
    requests:
      storage: 5Gi
